<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>670d0e64-2dc8-4a06-b054-5c7a221c59a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/div/div[2]/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a48160d9-5f21-42df-b272-cd01a2be72ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accounts.lambdatest.com/login</value>
      <webElementGuid>487ddc69-bbfa-4348-8c8d-4081ad4557cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop:block desktop:ml-0 desktop:mt-10 nav-link inline-block py-15 px-60 text-size-16 font-medium ml-30 fromipad:ml-20 text-ltBlack-50 desktop:border border-black desktop:text-center desktop:py-10 desktop:rounded border rounded login hover:bg-black hover:text-white</value>
      <webElementGuid>68438601-33fd-47bf-b058-caa692de9e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>0894ba65-8bba-4a3d-9849-fc77fda564e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;container&quot;]/div[@class=&quot;px-2 desktop:py-15&quot;]/div[@class=&quot;flex -mx-2 items-center desktop:block&quot;]/div[@class=&quot;header__menu px-2 desktop:w-full&quot;]/div[@class=&quot;desktop:mt-20 desktop:text-left desktop:hidden&quot;]/div[@class=&quot;flex items-center desktop:block&quot;]/div[@class=&quot;w-4/12 md:text-right desktop:text-left desktop:w-full smtablet:px-15&quot;]/a[@class=&quot;desktop:block desktop:ml-0 desktop:mt-10 nav-link inline-block py-15 px-60 text-size-16 font-medium ml-30 fromipad:ml-20 text-ltBlack-50 desktop:border border-black desktop:text-center desktop:py-10 desktop:rounded border rounded login hover:bg-black hover:text-white&quot;]</value>
      <webElementGuid>3c235336-18f2-4121-a12f-b99e4d36e44a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>93b3b491-f450-4d96-83af-72fb6bfc0872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>df77201d-5925-4d7e-acc0-60f6ac4fc551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[1]</value>
      <webElementGuid>4a27af86-030d-4b56-bb95-9efe0ec556ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing Advisor'])[1]/following::a[2]</value>
      <webElementGuid>05e25257-49a5-4d43-83bd-0fa1c58bf636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Free Testing'])[1]/preceding::a[1]</value>
      <webElementGuid>81bfa22b-e266-4cfb-ab5c-e63dedb96b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Browser Testing Cloud'])[1]/preceding::a[2]</value>
      <webElementGuid>05382ab5-bfbd-466a-a1e2-7d134b819a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>c6deeb0d-1ab6-405f-bb92-faf292627a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accounts.lambdatest.com/login')]</value>
      <webElementGuid>b915a0d6-2cb7-4879-9e0a-e1e7612a3eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>92bdcc8e-a148-44ce-aa2b-43ac42f3f4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accounts.lambdatest.com/login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>05228b5c-5341-4349-8a00-924fb9bb68df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
