<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Finland</name>
   <tag></tag>
   <elementGuidId>4df14f94-4a22-403d-8dd3-d4c9e6377fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div[2]/div/header/div[2]/nav[2]/div/span/div/div[2]/a[52]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0121fb1b-c1d0-4640-9a76-fbb55f4f601e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.pwc.fi</value>
      <webElementGuid>f746d851-1828-4f45-a2f1-05f4c583a7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Finland</value>
      <webElementGuid>1b257d6c-1440-4929-82f6-f299a2d89b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finland</value>
      <webElementGuid>1881407f-273b-4209-9c24-1c6fdaa8f755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[1]/div[@class=&quot;slim-page-header-v2 parbase section&quot;]/div[@class=&quot;headerv2-container&quot;]/header[@class=&quot;slimheader-v2&quot;]/div[@class=&quot;slim-navigation&quot;]/nav[@class=&quot;nav-secondary search-hide&quot;]/div[@class=&quot;location-options&quot;]/span[@class=&quot;option-country levelOneLink option-country--open&quot;]/div[@class=&quot;territory-selector&quot;]/div[@class=&quot;territory-selector-list levelOneLink&quot;]/a[52]</value>
      <webElementGuid>db9addce-5598-4290-8aad-b0fc19ce9ff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div[2]/div/header/div[2]/nav[2]/div/span/div/div[2]/a[52]</value>
      <webElementGuid>c393ff69-c048-4534-baed-1b04716308f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Finland')]</value>
      <webElementGuid>5c01528a-f4bf-4731-aa99-9db403b0d46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estonia'])[1]/following::a[1]</value>
      <webElementGuid>4407fd23-4e61-4310-9c41-e5cada82065d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equatorial Guinea'])[1]/following::a[2]</value>
      <webElementGuid>d3200ec4-75af-4869-a5da-29328ca4e357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='France'])[1]/preceding::a[1]</value>
      <webElementGuid>bb818c80-41a0-458e-bd45-b756f2dad1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabon'])[1]/preceding::a[2]</value>
      <webElementGuid>a4c97f9c-de62-49c0-b19c-1cb7ceabe829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finland']/parent::*</value>
      <webElementGuid>b76007ad-d818-491f-8b5b-681d282d2da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.pwc.fi')]</value>
      <webElementGuid>ad286606-f6ef-42be-b7ea-3a7098e33e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[52]</value>
      <webElementGuid>db5bf818-0c84-4229-af61-d10c9abfcef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.pwc.fi' and (text() = 'Finland' or . = 'Finland')]</value>
      <webElementGuid>1836ec22-3d66-433c-bdea-aabbf39ce8c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
